In [19]:
import numpy
import scipy.special

In [31]:
class neuralNetwork:
    def __init__(self, input_nodes, hidden_nodes, output_nodes, learning_rate):
        #initalising the size of the network
        self.inodes = input_nodes
        self.hnodes = hidden_nodes
        self.onodes = output_nodes
        #learning rate of the network
        self.lr = learning_rate
        #initializing weight matrix
        self.wih = numpy.random.normal(0.0, pow(self.hnodes, -0.5), (self.hnodes, self.inodes))
        self.who = numpy.random.normal(0.0, pow(self.onodes, -0.5), (self.onodes, self.hnodes))
        self.activation_function = lambda x: scipy.special.expit(x)
        pass
    
    def train(self, inputs_list, targets_list):
        inputs = numpy.array(inputs_list, ndmin=2).T
        targets = numpy.array(targets_list, ndmin=2).T
        
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        
        output_errors = targets - final_outputs
        
        hidden_errors = numpy.dot(self.who.T, output_errors)
        self.who += self.lr * numpy.dot((output_errors * final_outputs * (1.0 - final_outputs)), numpy.transpose(hidden_outputs))
        self.wih += self.lr * numpy.dot((hidden_errors * hidden_outputs * (1.0 - hidden_outputs)), numpy.transpose(inputs))
        pass
    
    def query(self, inputs_list):
        #calculating the hidden layer
        inputs = numpy.array(inputs_list, ndmin=2).T
        print(inputs)
        hidden_inputs = numpy.dot(self.wih, inputs)
        hidden_outputs = self.activation_function(hidden_inputs)
        
        final_inputs = numpy.dot(self.who, hidden_outputs)
        final_outputs = self.activation_function(final_inputs)
        return final_outputs
        
        
    

In [64]:
n = neuralNetwork(3,3,3,0.3)
print(n.inodes)
print(n.wih)
print(n.who)

n.query([1.0, 0.5, -1.5])

3
[[ 0.88923912 -0.30699592 -0.40060124]
 [-0.19893653 -0.11039902 -0.09678409]
 [ 0.52927193 -0.52796498 -0.17361025]]
[[-0.42168373  0.28993933  0.22729086]
 [ 0.3841786   0.4389306  -0.09916382]
 [ 0.36827148  0.39706645 -0.77901726]]
[[ 1. ]
 [ 0.5]
 [-1.5]]


array([[0.48649838],
       [0.61050691],
       [0.49744462]])

In [65]:
for t in range(100):
    n.train([1.0, 0.5, -0.75], [0.8, 0.2, -0.3])
n.query([1.0, 0.5, -0.75])

[[ 1.  ]
 [ 0.5 ]
 [-0.75]]


array([[0.78030472],
       [0.23336802],
       [0.0467941 ]])

In [66]:
data_file = open("mnist_train_100.csv", 'r')
data_list = data_file.readlines()
data_file.close()

In [67]:
len(data_list)

100